### ISSUE TITLE
Configuration with name 'testSources' not found.

### ISSUE THREAD

**Issue by alixwar** [hauner/gradle-plugins#2]
When trying to build my multi-module gradle project I get this error:

```
[15:41:37][Step 2/2] 13:41:37.957 [ERROR] [org.gradle.BuildExceptionReporter] 
[15:41:37][Step 2/2] 13:41:37.959 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
[15:41:37][Step 2/2] 13:41:37.959 [ERROR] [org.gradle.BuildExceptionReporter] 
[15:41:37][Step 2/2] 13:41:37.960 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
[15:41:37][Step 2/2] 13:41:37.961 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/app/domain/build.gradle' line: 44
[15:41:37][Step 2/2] 13:41:37.961 [ERROR] [org.gradle.BuildExceptionReporter] 
[15:41:37][Step 2/2] 13:41:37.961 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
[15:41:37][Step 2/2] 13:41:37.961 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating project ':domain'.
[15:41:37][Step 2/2] 13:41:37.961 [ERROR] [org.gradle.BuildExceptionReporter] > Failed to apply plugin [id 'com.github.hauner.jarTest']
[15:41:37][Step 2/2] 13:41:37.961 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not find property 'testClasses' on project ':domain'.
[15:41:37][Step 2/2] 13:41:37.962 [ERROR] [org.gradle.BuildExceptionReporter] 
[15:41:37][Step 2/2] 13:41:37.962 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':domain'.
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:150)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:155)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:521)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:589)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:581)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:236)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:130)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at build_1348upw6i7sw15c3c6pndwyfd.run(/app/application/build.gradle:2)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:150)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:155)
[15:41:37][Step 2/2] 13:41:37.963 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:521)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:92)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
[15:41:37][Step 2/2] 13:41:37.967 [LIFECYCLE] [org.gradle.BuildResultLogger] 
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.internal.Factories$1.create(Factories.java:22)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
[15:41:37][Step 2/2] 13:41:37.967 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
[15:41:37][Step 2/2] 13:41:37.967 [LIFECYCLE] [org.gradle.BuildResultLogger] 
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
[15:41:37][Step 2/2] 13:41:37.968 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 7.131 secs
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
[15:41:37][Step 2/2] 13:41:37.964 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.Main.doAction(Main.java:33)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.github.hauner.jarTest']
[15:41:37][Step 2/2] 13:41:37.965 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:153)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at build_9gjspai3miti7ycel9yqmixze.run(/app/domain/build.gradle:44)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   ... 66 more
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: groovy.lang.MissingPropertyException: Could not find property 'testClasses' on project ':domain'.
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at com.github.hauner.gradle.jartest.JarTestPlugin.apply(JarTestPlugin.groovy:30)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at com.github.hauner.gradle.jartest.JarTestPlugin.apply(JarTestPlugin.groovy)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
[15:41:37][Step 2/2] 13:41:37.966 [ERROR] [org.gradle.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
[15:41:37][Step 2/2] 13:41:37.967 [ERROR] [org.gradle.BuildExceptionReporter]   ... 77 more
[15:41:37][Step 2/2] 13:41:37.967 [ERROR] [org.gradle.BuildExceptionReporter] 
```

My config is simple:

(module 'domain'):
`apply plugin: "com.github.hauner.jarTest"`

```
buildscript {
    repositories {
        maven {
            url "..."
        }
    }
    dependencies {
        classpath "gradle.plugin.gradle-plugins:jartest:1.0.1"
    }
}
```

and in the other module using the test-jar from domain:

`testCompile project (path: ':domain', configuration: 'testArchives')`

Any ideas?

I'm using Gradle 2.11

**Comment by hauner** [comment]
The plugin depends on a language plugin. It requires the `testCompile`configuration, `testClasses` task and `sourceSets`.  

Do you have a language plugin in your `domain` project?

Another issue might be mixing `apply` and `plugin {}` configurations. It is possible that gradle apply's `jartest` before the language plugin. See https://github.com/hauner/gradle-plugins/issues/1#issuecomment-169481444
